language: node_js
node_js: 10 # latest stable release
install:
  - npm ci
  - npm run bootstrap
script:
  - npm run lint
  - npm test
  - npm run ci:commitlint
  - npx lerna run build
cache:
  directories:
    - ~/.npm
