language: node_js
node_js: 10 # latest stable release
install:
  - npm ci
  - npm run bootstrap
script:
  - npm test
  - npm run lint
  # TODO reenable when commitlint supports lerna 3
  # - npm run ci:commitlint
cache:
  directories:
    - ~/.npm
